export const siteConfig = {
  brandName: "Moonlit Loops",
  subtitle: "by Jyotsna",
  creatorName: "Jyotsna",
  tagline: "Young hands. Big imagination. Beautiful crochet.",
  whatsappNumber: "919764006232",
  whatsappDisplay: "+91 97640 06232",
  email: "moonlitloopsbyjyotsna@gmail.com",
  instagramHandle: "",
  instagramUrl: "",
  currencySymbol: "₹",
  currencyCode: "INR",
  location: "Pune, Maharashtra, India",
  shippingNote: "Made to order • Shipping across India",
  noticeBanner: "Handmade crochet • Made to order • India-first launch",
};
